hostPath:
  dags: "/Users/soufiane/Documents/GitHub/local-dev-airflow/dags"

airflow:
  dags:
    persistence:
      enabled: true
      existingClaim: airflow-dags
      storageClassName: local-storage 
  
